name: Continuous Integration

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  pre_test:
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run test
      - run: npx next build
